# Generated by Django 5.0.7 on 2024-12-18 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Home_Page", "0017_book_detail_2_book_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchEmbedModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TitleEmbed", models.JSONField(null=True)),
                (
                    "Book",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="title_embed",
                        to="Home_Page.book_detail_2",
                    ),
                ),
            ],
        ),
    ]
