# Generated by Django 5.0.7 on 2024-08-24 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("login_and_signup", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userinfo",
            old_name="emailAdderss",
            new_name="emailAddress",
        ),
    ]
