# Generated by Django 5.0.7 on 2024-12-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home_Page", "0017_book_detail_2_book_id"),
        ("login_and_signup", "0003_remove_userinfo_id_userinfo_userid"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="readLater",
            field=models.ManyToManyField(
                related_name="user_readLater", to="Home_Page.book_detail_2"
            ),
        ),
    ]
