# Generated by Django 5.0.7 on 2024-10-14 04:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Home_Page", "0003_alter_book_detail_publish_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book_detail",
            old_name="Publish_date",
            new_name="Publish_year",
        ),
    ]
