# Generated by Django 5.0.7 on 2024-10-20 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home_Page", "0004_rename_publish_date_book_detail_publish_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="book_detail",
            name="Rating",
            field=models.IntegerField(
                default=0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="book_detail",
            name="Rating_Count",
            field=models.BigIntegerField(
                default=0,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
