# Generated by Django 5.0.7 on 2024-10-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home_Page", "0006_remove_book_detail_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="book_detail",
            name="Genre",
            field=models.CharField(
                choices=[
                    ("biography", "biography"),
                    ("children", "childrean"),
                    ("fantasy", "fantasy"),
                    ("fiction", "fiction"),
                    ("mystery", "mystery"),
                    ("non-fiction", "non-fiction"),
                    ("romance", "romance"),
                    ("science", "science"),
                    ("science fiction", "science fiction"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
