# Generated by Django 5.0.7 on 2024-10-21 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home_Page", "0007_book_detail_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="book_detail",
            name="weighted_rating",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="book_detail",
            name="Rating",
            field=models.FloatField(
                default=0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
