# Generated by Django 5.0.7 on 2024-10-21 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Home_Page", "0008_book_detail_weighted_rating_alter_book_detail_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book_detail",
            name="weighted_rating",
        ),
    ]
