# Generated by Django 5.0.7 on 2024-10-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Home_Page", "0009_remove_book_detail_weighted_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="book_detail",
            name="weighted_avg",
            field=models.FloatField(null=True),
        ),
    ]
