# Generated by Django 5.0.7 on 2024-10-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home_Page", "0011_book_detail_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book_detail_2",
            name="Genre",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
