# Generated by Django 5.0.7 on 2024-11-09 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home_Page", "0014_bestseller"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookembedModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Embedding", models.JSONField(null=True)),
                (
                    "Book",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="Home_Page.book_detail_2",
                    ),
                ),
            ],
        ),
    ]
