# Generated by Django 5.0.7 on 2024-11-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home_Page", "0015_bookembedmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookembedmodel",
            name="SimScore",
            field=models.JSONField(null=True),
        ),
    ]
