# Generated by Django 5.0.7 on 2024-11-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home_Page", "0016_bookembedmodel_simscore"),
    ]

    operations = [
        migrations.AddField(
            model_name="book_detail_2",
            name="book_id",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
